### ISSUE TITLE
Missing UIManager GameObject and DemoWorld

### ISSUE THREAD

**Issue by danmartinez78** [googlecreativelab/arexperiments-portal-painter#2]
I'm not seeing where these objects are included in the unity project. Am I missing something?

**Comment by friej715** [comment]
I think you might still be in Unity's default blank scene. You'll want to navigate to the Main scene included in the project, in the Assets folder. Give me a shout if that doesn't work.

**Comment by cdfasnacht** [comment]
So this is the scene I'm seeing through the app.

![screenshot_20170906-154835](https://user-images.githubusercontent.com/31708599/30131637-7ef25c18-931b-11e7-86c6-9d8c748ce9b6.png)

I was expecting the forest scene with mushrooms and a well as seen here:
https://github.com/googlecreativelab/arexperiments-portal-painter/blob/master/portal-painter.gif

How can I get that scene into the app?

**Comment by friej715** [comment]
Those assets are from other folks, so we didn't package them with the open source app. But you can find the materials to recreate those scenes here:

[Stylized Nature Pack](https://www.assetstore.unity3d.com/en/#!/content/37457)
[What Does the Fox Say?](https://vr.google.com/objects/5GOJhwOZ5jf)
[Low Poly Island](https://www.assetstore.unity3d.com/en/#!/content/87818)
[Low Poly Asteroid Pack](https://www.assetstore.unity3d.com/en/#!/content/83016)
